Dev
SeulgiLee12/MineSweeper pull request #2
Opened 2023-11-15 13:40 UTC by SeulgiLee12

지뢰찾기 리펙토링 코드 입니다

2023-11-17 14:44 UTC, minsoowoo requested changes

2023-11-17 14:44 UTC, minsoowoo commented on src/MineSweeperBoard.java
> +    int MINE_NUM = 0;
대부분의 프로그래밍 언어는 상수 변수를 대문자로, 일반 변수는 소문자로 표기합니다. BOARD_ROW나 MINE_NUM 변수는 일반변수인데 상수 값인것 처럼 헷갈리네요. boardRow 같이 자바 스타일의 일반 변수 표기로 변경하는 것이 좋아보여요.

2023-11-17 14:44 UTC, minsoowoo commented on src/MineSweeperBoard.java
> +    int NUMBER_OF_MINES_AROUND_CELL = 0;
NUMBER_OF_MINES_AROUND_CELL 변수도 일반 변수니까 카멜 표기법으로 변경하는 것이 좋을 것 같네요.

2023-11-17 14:44 UTC, minsoowoo commented on src/MineSweeperBoard.java
> +            for (int column=0; column<BOARD_ROW; column++)
BOARD_ROW 라는 이름이면 가로줄 (열)의 정보를 가지고 있을 것 같은데 여기서는 가로 세로를 동일하게 사용하고 있죠. column < BOARD_ROW 는 잘못된 정보끼리 비교하는 것 같아서 혼란을 유발합니다. ROW를 size나 length 등의 단어로 변경하는 것이 헷갈리지 않을 것 같아요.

2023-11-17 14:44 UTC, minsoowoo commented on src/MineSweeperBoard.java
> +                    if (board[row+rowPattern][col+colPattern].equals(MINE)) NUMBER_OF_MINES_AROUND_CELL++;
for문이랑 if문이 여러번 중첩되고 들여쓰기가 많이 들어가서 살짝 불만이긴 합니다만... for문 2개는 한 세트니까 넘어가고, if문을 함수로 따로 만들려고 하니 인자가 많아서 좀 고민이 되는 부분이네요. 나중에라도 이 부분 중첩이 깔끔하게 정리되는 코드가 생각나면 알려줄게요.
if문 조건으로 여러 개의 && 비교가 나와서 한 눈에 파악하기가 어려운 것 같아요. 저는 이런 경우 조건문을 단순화시켜서 여러줄로 나누거나, && 연산때마다 줄바꿈을 하거나, 괄호()로 구분하거나 합니다.
```
if (row+rowPattern >= 0 &&
  row+rowPattern < BOARD_ROW &&
  col+colPattern >= 0 && 
...
if ( (row+rowPattern >= 0) && (row+rowPattern < BOARD_ROW) && ...
```
조건문을 단순하게 변경하기 어렵다면 위 두가지 방법 중의 하나를 사용해서 가독성을 올리는 것이 어떨까요?

2023-11-17 14:44 UTC, minsoowoo commented on src/MineSweeperBoard.java
> +        setMinesPosition();
함수 순서는 보통은 크게 신경쓸 필요는 없지만 이 경우에는 함수가 순차적으로 나오므로 가능한 함수를 순서대로 나열하면 읽기가 편합니다. 특히 makeAndPrindBoard()가 아래쪽에 있다보니 setBoardRowAndMineNumbers() 읽고 다시 내려와서 그다음 함수인 makeEmptyBoard() 함수 확인하고 또 올라가서 찾는 방식이 계속 반복되네요. 최소한 makeAndPrindBoard() 함수라도 가장 위로 올려주면 그나마 읽는 순서가 편해지고 스크롤을 덜 할 것 같은데, 어떻게 생각하나요?

2023-11-18 13:45 UTC, asdfg1209 commented
수정 사항 수정 했습니다!

2023-11-19 03:11 UTC, minsoowoo approved these changes
수정한 코드 확인했어요. 훨씬 보기 좋은 것 같네요.
승인합니다.
수고했어요~ 👍

2023-11-19 03:11 UTC, merged